backend:
  name: git-gateway
  branch: main
locale: "fr"
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "fiches"
    label: "Fiches"
    folder: "fiches"
    create: true
    extension: "md"
    fields:
      - {label: "Titre", name: "title", widget: "string", required: true}
      - {label: "Identifiant (14 chiffres)", name: "id",  widget: "number", pattern: [".{14}","L'identifiant doit être une chaîne de caractères unique composée de 14 chiffres"], required: true}
      - {label: "Type", name: "type", widget: "string", default: "documentation", required: true}
      - {label: "Mots-clés", name: "tags", widget: "list", required: false}
      - {label: "Contenu", name: body, widget: "markdown"}